# Generated by Django 3.2 on 2022-01-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prdouct',
            new_name='Product',
        ),
    ]
