# Generated by Django 3.2 on 2022-02-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220222_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_id',
            new_name='review_title',
        ),
    ]
