# Generated by Django 3.2 on 2022-02-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_review_id_review_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_title',
            new_name='review_id',
        ),
    ]
